<div id="preloader-overlay"</div>
<div class="container">
  <div id="r01"><img src="<?php echo base_url("/assets/images/immortal-bed/r01.png"); ?>" /></div>
  <div id="r02"><img src="<?php echo base_url("/assets/images/immortal-bed/r02.png"); ?>" /></div>
  <div id="r03"><img src="<?php echo base_url("/assets/images/immortal-bed/r03.png"); ?>" /></div>
  <div id="r04"><img src="<?php echo base_url("/assets/images/immortal-bed/r04.png"); ?>" /></div>
  <div id="r05"><img src="<?php echo base_url("/assets/images/immortal-bed/r05.png"); ?>" /></div>
  <div id="r06"><img src="<?php echo base_url("/assets/images/immortal-bed/r06.png"); ?>" /></div>
  <div id="r07"><img src="<?php echo base_url("/assets/images/immortal-bed/r07.png"); ?>" /></div>
  <div id="r08"><img src="<?php echo base_url("/assets/images/immortal-bed/r08.png"); ?>" /></div>
  <div id="r09"><img src="<?php echo base_url("/assets/images/immortal-bed/r09.png"); ?>" /></div>
  <div id="r10"><img src="<?php echo base_url("/assets/images/immortal-bed/r10.png"); ?>" /></div>
  <div id="r11"><img src="<?php echo base_url("/assets/images/immortal-bed/r11.png"); ?>" /></div>
  <div id="r12"><img src="<?php echo base_url("/assets/images/immortal-bed/r12.png"); ?>" /></div>
  <div id="r13"><img src="<?php echo base_url("/assets/images/immortal-bed/r13.png"); ?>" /></div>
  <div id="r14"><img src="<?php echo base_url("/assets/images/immortal-bed/r14.png"); ?>" /></div>
  <div id="r15"><img src="<?php echo base_url("/assets/images/immortal-bed/r15.png"); ?>" /></div>
  <div id="r16"><img src="<?php echo base_url("/assets/images/immortal-bed/r16.png"); ?>" /></div>
  <div id="r17"><img src="<?php echo base_url("/assets/images/immortal-bed/r17.png"); ?>" /></div>
  <div id="r18"><img src="<?php echo base_url("/assets/images/immortal-bed/r18.png"); ?>" /></div>
  <div id="r19"><img src="<?php echo base_url("/assets/images/immortal-bed/r19.png"); ?>" /></div>
  <div id="r20"><img src="<?php echo base_url("/assets/images/immortal-bed/r20.png"); ?>" /></div>
  <div id="r21"><img src="<?php echo base_url("/assets/images/immortal-bed/r21.png"); ?>" /></div>
  <div id="r22"><img src="<?php echo base_url("/assets/images/immortal-bed/r22.png"); ?>" /></div>
  <div id="r23"><img src="<?php echo base_url("/assets/images/immortal-bed/r23.png"); ?>" /></div>
  <div id="r24"><img src="<?php echo base_url("/assets/images/immortal-bed/r24.png"); ?>" /></div>
  <div id="r25"><img src="<?php echo base_url("/assets/images/immortal-bed/r25.png"); ?>" /></div>
  <div id="r26"><img src="<?php echo base_url("/assets/images/immortal-bed/r26.png"); ?>" /></div>
  <div id="r27"><img src="<?php echo base_url("/assets/images/immortal-bed/r27.png"); ?>" /></div>
  <div id="r28"><img src="<?php echo base_url("/assets/images/immortal-bed/r28.png"); ?>" /></div>
  <div id="r29"><img src="<?php echo base_url("/assets/images/immortal-bed/r29.png"); ?>" /></div>
  <div id="r30"><img src="<?php echo base_url("/assets/images/immortal-bed/r30.png"); ?>" /></div>
  <div id="r31"><img src="<?php echo base_url("/assets/images/immortal-bed/r31.png"); ?>" /></div>
  <div id="r32"><img src="<?php echo base_url("/assets/images/immortal-bed/r32.png"); ?>" /></div>
  <div id="r33"><img src="<?php echo base_url("/assets/images/immortal-bed/r33.png"); ?>" /></div>
  <div id="r34"><img src="<?php echo base_url("/assets/images/immortal-bed/r34.png"); ?>" /></div>
  <div id="r35"><img src="<?php echo base_url("/assets/images/immortal-bed/r35.png"); ?>" /></div>
  <div id="r36"><img src="<?php echo base_url("/assets/images/immortal-bed/r36.png"); ?>" /></div>
  <div id="r37"><img src="<?php echo base_url("/assets/images/immortal-bed/r37.png"); ?>" /></div>
  <div id="r38"><img src="<?php echo base_url("/assets/images/immortal-bed/r38.png"); ?>" /></div>
  <div id="r39"><img src="<?php echo base_url("/assets/images/immortal-bed/r39.png"); ?>" /></div>
  <div id="r40"><img src="<?php echo base_url("/assets/images/immortal-bed/r40.png"); ?>" /></div>
  <div id="r41"><img src="<?php echo base_url("/assets/images/immortal-bed/r41.png"); ?>" /></div>
  <div id="r42"><img src="<?php echo base_url("/assets/images/immortal-bed/r42.png"); ?>" /></div>
  <div id="r43"><img src="<?php echo base_url("/assets/images/immortal-bed/r43.png"); ?>" /></div>
  <div id="r44"><img src="<?php echo base_url("/assets/images/immortal-bed/r44.png"); ?>" /></div>
  <div id="r45"><img src="<?php echo base_url("/assets/images/immortal-bed/r45.png"); ?>" /></div>
  <div id="r46"><img src="<?php echo base_url("/assets/images/immortal-bed/r46.png"); ?>" /></div>
  <div id="r47"><img src="<?php echo base_url("/assets/images/immortal-bed/r47.png"); ?>" /></div>
  <div id="r48"><img src="<?php echo base_url("/assets/images/immortal-bed/r48.png"); ?>" /></div>
  <div id="trees"><img src="<?php echo base_url("/assets/images/immortal-bed/trees.png"); ?>" /></div>
</div>
